spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.dealhunter:8848
      config:
        server-addr: nacos-service.dealhunter:8848

  application:
    name: dh-email

  rabbitmq:
    host: rabbitmq-service.dealhunter
    port: 5672
    username: guest
    password: guest
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: deal.hunter.platform@gmail.com
    password: aihubrvcgrjlbzmv
    properties:
      mail:
        smtp:
          auth: true
          starttles:
            enable: true

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api/email

queue:
  name: email




