spring:
  cloud:
    nacos:
      confg:
        server-addr: 127.0.0.1:8848

  application:
    name: dh-brand

  datasource:
    url: jdbc:mysql://167.172.71.33:30557/dh-brand?allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: wodemima

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

server:
  address: 0.0.0.0
  port: 8102
  servlet:
    context-path: /api/brand

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  default-flat-param-object: false

