spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.dealhunter:8848
      config:
        server-addr: nacos-service.dealhunter:8848

  application:
    name: dh-product

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  sql:
    init:
      mode: always
  datasource:
    url: jdbc:mysql://dh-product-mysql-service.dealhunter:3306/dh-product?allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: wodemima
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
      ddl-auto: update
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

  rabbitmq:
    host: rabbitmq-service.dealhunter
    port: 5672
    username: guest
    password: guest

queue:
  name: email

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api/product

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
  default-flat-param-object: false

minio:
  access_key: YOURACCESSKEY
  secret_key: YOURSECRETKEY
  bucket: dealhunter
  end_point: minio-service.dealhunter：9000