spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos-service.dealhunter:8848
      config:
        server-addr: nacos-service.dealhunter:8848
    gateway:
      routes:
        - id: dh-brand
          uri: lb://dh-brand
          predicates:
            - Path=/api/brand/**
        - id: dh-user
          uri: lb://dh-user
          predicates:
            - Path=/api/user/**
        - id: dh-product
          uri: lb://dh-product
          predicates:
            - Path=/api/product/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods: "*"

  application:
    name: dh-gateway
  main:
    web-application-type: reactive

server:
  port: 8080

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - dh-gateway

system:
  properties:
    whitelist: /api/user/v3/api-docs/default,/api/user/login,/api/user/signup,/v3/api-docs/default,/api/brand/v3/api-docs/default,/api/product/v3/api-docs/default